/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../context/OrderContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/context/OrderContext`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard/cart`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard/detail`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard/notification`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard/profil`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard/table`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../context/OrderContext`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/context/OrderContext`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/user/dashboard/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/user/dashboard/detail`; params?: Router.UnknownOutputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/user/dashboard/notification`; params?: Router.UnknownOutputParams; } | { pathname: `/user/dashboard/profil`; params?: Router.UnknownOutputParams; } | { pathname: `/user/dashboard/table`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../context/OrderContext${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/dashboard${`?${string}` | `#${string}` | ''}` | `/context/OrderContext${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/user/dashboard/cart${`?${string}` | `#${string}` | ''}` | `/user/dashboard/detail${`?${string}` | `#${string}` | ''}` | `/user/dashboard${`?${string}` | `#${string}` | ''}` | `/user/dashboard/notification${`?${string}` | `#${string}` | ''}` | `/user/dashboard/profil${`?${string}` | `#${string}` | ''}` | `/user/dashboard/table${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../context/OrderContext`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/context/OrderContext`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard/cart`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard/detail`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard/notification`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard/profil`; params?: Router.UnknownInputParams; } | { pathname: `/user/dashboard/table`; params?: Router.UnknownInputParams; };
    }
  }
}
